Fixes #283 - Depuración
aledi/pitagoras pull request #288
Opened 2017-02-07 17:01 UTC by alexcris

2017-02-07 17:01 UTC, alexcris commented
falta lo de los colores @ecristerna

2017-02-07 17:13 UTC, ecristerna requested changes
Hay que ponerle una alerta cuando vaya a haber un cambio en cualquiera de los dos checkbox. También, al lado del checkbox, poner el nombre de quien hizo el último cambio y la fecha.

2017-02-07 21:00 UTC, alexcris commented
@ecristerna último cambio de cualquier detalle del contrato? o de esos checkboxes?

2017-02-07 21:00 UTC, ecristerna commented
de esos checkboxes

2017-02-10 01:35 UTC, alexcris commented
ya quedaron los colores, @ecristerna

2017-02-10 01:39 UTC, ecristerna approved these changes

2017-02-10 01:40 UTC, merged